apiVersion: v1
kind: Namespace
metadata:
  name:  reciter
  labels:
    name:  reciter
    environment: dev
---
apiVersion: v1
kind: Service
metadata:
  name: reciter-pm
  labels:
    app: reciter-pm
spec:
  ports:
    - port: 8081
  selector:
    app: reciter-pm
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: reciter-pm
  labels:
    app: reciter-pm
spec:
  selector:
    matchLabels:
      app: reciter-pm
      tier: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: reciter-pm
        tier: frontend
    spec:
      containers:
      - image: reciter-pub-manager:1.0
        name: reciter-pm
        imagePullPolicy: Never
        # env:
        # - name: WORDPRESS_DB_HOST
        #   value: wordpress-mysql
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: 8081
          name: reciter-pm
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reciter-pm
  namespace: reciter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reciter-pm
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50